/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void pyramid1() {
        PyramidMaker pyramidMaker = new PyramidMaker(1);
        String result = pyramidMaker.create();
        assertEquals("\n*\n", result);
    }

    @Test
    void pyramid3() {
        PyramidMaker pyramidMaker = new PyramidMaker(3);
        String result = pyramidMaker.create();
        assertEquals("\n*\n**\n* *\n", result);
    }

    @Test
    void pyramid10() {
        PyramidMaker pyramidMaker = new PyramidMaker(10);
        String result = pyramidMaker.create();
        assertEquals("\n*\n**\n* *\n****\n* * *\n******\n* * * *\n********\n* * * * *\n**********\n", result);
    }
}
